# Generated by Django 4.2.10 on 2025-02-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_l2info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=1)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('datenais', models.DateField()),
                ('dateins', models.DateField(auto_now=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=3)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_l2info.promotion')),
            ],
        ),
    ]
